### PR TITLE
Fix 401-403 for automatic cookies

### PR DESCRIPTION
**Pull request by HaoK**
Cookies was overriding the base impl of AuthenticateAsync so the flag wasn't getting set which made the 401-403 check fail...  

Definitely some smell here, filed https://github.com/aspnet/Security/issues/273 to fix

cc @blowdart @Tratcher @lodejard

### CODE REVIEW

**Comment by HaoK** [comment]
Fixes https://github.com/aspnet/Security/issues/246

**Comment by HaoK** [comment]
@blowdart do we want this for beta 5 (aka today?)

**Comment by blowdart** [comment]
Yea, we should get it in.

**Comment by HaoK** [comment]
merged e54d088c462b18c76a8f218b11ea2614e41622b6

**Pull request closed without merging**
