### PR TITLE
Tweak SecurityHelper for MVC usage

### PR DESCRIPTION
**Pull request by HaoK**
Pass/Return HttpContext.user instead of manipulating the context to make this reusable for MVC

cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit: There's no behavior change, correct?

**Comment by HaoK** [comment]
I certainly hope not!

**Comment by HaoK** [comment]
While I'm touching this, should we consider renaming the helper?  We could even make it an extension method on ClaimsPrincipal instead?

**Comment by Tratcher** [comment]
PrincipalHelper?
I don't recommend changing it to an extension method.

**Comment by HaoK** [comment]
If we are going to keep helper I guess security isn't bad

**Comment by HaoK** [comment]
5e92de8009901aa73ccdbd1d9ebe4fc89dbc7add

**Pull request closed without merging**
