### PR TITLE
Revert obsoleting CookieAuthenticationOptions.ExpireTimeSpan

### PR DESCRIPTION
**Pull request by natemcmaster**
`CookieAuthenticationOptions.Cookie.Expiration` is conceptually different from `CookieAuthenticationOptions.ExpireTimeSpan`.

Un-oboleting the property and updating xmldocs.

### CODE REVIEW

**Comment by HaoK** [comment]
Changes look fine, but are we missing some test coverage since shouldn't a test have to be updated? :)  They probably have always been missing, but maybe we should take this opportunity to add 1-2 basic tests that actually enforce the behavior we expect?

**Comment by natemcmaster** [comment]
A bunch tests in CookieTests.cs were updated. Which behavior should we test for that isn't already covered?

**Comment by HaoK** [comment]
I mean the Cookie.Expires property I guess, or is that the one we basically ignore?

**Comment by natemcmaster** [comment]
Yeah, that's the one we currently ignore. I left this unchanged:  https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication.Cookies/CookieAuthenticationHandler.cs#L180-L181

**Comment by HaoK** [comment]
Okay, worth adding a single test to capture that we ignore CookieBuilder.Expires so we don't regress this accidentally in the future?

**Comment by natemcmaster** [comment]
Added a test.

**Comment by natemcmaster** [comment]
Btw, let's use https://github.com/aspnet/Security/issues/1293 to clarify what CookieBuilder.Expiration should mean. We can address this after 2.0.0. For now, we'll just ignore its value.

**Pull request merged**
