### PR TITLE
React to Options, pubternal ConfigureDefaultOptions

### PR DESCRIPTION
**Pull request by HaoK**
Depends on https://github.com/aspnet/Options/pull/192

@Tratcher

### CODE REVIEW

**Comment by PinpointTownes** [comment]
So we have `ConfigureDefaultOptions`, `IConfigureOptions` and `IPostConfigureOptions`? :sweat_smile: 

At this point, wouldn't having a single interface/class w/ an `Order` property be cleaner?

**Comment by HaoK** [comment]
We had order originally in Options early on, it was far from a panacea, it was just convention based with ints instead of names...

ConfigureDefaultOptions is not meant for external use, hence the infrastructure namespace/no interface.  People should go through the normal IConfigureOptions route.  PostConfigure is when you want to do stuff after people have configured things (aka fixup/validation/normalize set up some defaults).  Its much harder to mess ordering up since PostConfigures should used sparingly...

That said, it wouldn't surprise me if we eventually add more lifecycles if there's a compelling need...

**Comment by HaoK** [comment]
@Tratcher this change is just hopefully making it clear that what was formerly known as IInitializeOptions, actually runs AFTER configure...  Lots of people assumed it would run first :(

**Comment by Tratcher** [comment]
Finalizer? Validator?

**Comment by HaoK** [comment]
Yeah this was discussed ad nauseam with the PMs yesterday and they settled on the clear (but ugly) name

**Comment by HaoK** [comment]
db9ae6263233e1d95245cb911614d0e20a12edfa

**Pull request closed without merging**
