### PR TITLE
Remove obsolete apis

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Security/issues/1421
https://github.com/aspnet/Security/issues/1631
https://github.com/aspnet/Security/issues/1292
https://github.com/aspnet/Security/issues/1221

### CODE REVIEW

**Comment by Tratcher** [comment]
Post an announcement.

Not waiting for reviews?

**Comment by HaoK** [comment]
Not if it has to go in today :)  I figure any review feedback I can address afterwards

**Comment by HaoK** [comment]
This has potential to break things, so I'd rather see any issues early in the build before a weekend is the main reason

**Comment by HaoK** [comment]
I'll post an announcement post mondo jump

**Pull request merged**
