### PR TITLE
Update OIDC to v1.0

### PR DESCRIPTION
**Pull request by Tratcher**
#808 @danroth27 @Eilon @DamianEdwards @muratg @vibronet @brentschmaltz @tushargupta51

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit: for this change.

@muratg does anything need to change in packages.csv for this?

**Comment by muratg** [comment]
@Eilon No, since the package name stays the same, no change in packages.csv is required.

**Comment by Eilon** [comment]
Thanks!

**Comment by dougbu** [comment]
Looks as if the `release` templates need to be updated to match. I just created a new Work and School project using our current tooling (:ok:, next) and the offline cache contained the `1.0.0-rc2-*` version of this package.
warning

Has that already been filed somewhere?

**Comment by danroth27** [comment]
@phenning Are you tracking this?

**Comment by phenning** [comment]
am now.

**Pull request merged**
