### PR TITLE
Encode ClientId/Secret in Basic Authorization Header per OIDC Spec

### PR DESCRIPTION
**Pull request by jdmichel**
- See 2.1.6.1 at http://openid.net/specs/openid-connect-basic-1_0.html#TokenRequest
 - Also removes the id and secret from the body of the message, although it's unclear if any Identity Providers will actually fail if its included both places, so might be worth leaving for compatibility even though it is against the spec.

Addresses #1737

### CODE REVIEW

**Comment by Tratcher** [comment]
Do you know of any services that don't work with the current bahavior?

**Comment by Tratcher** [comment]
And for that matter, any providers that this change works with?

**Comment by PinpointTownes** [comment]
> it's unclear if any Identity Providers will actually fail if its included both places, so might be worth leaving for compatibility even though it is against the spec.

No, don't do that... it's illegal and standard-compliant servers will reject your request if you do that (e.g my 2 OIDC server libs will return a `Multiple client credentials cannot be specified.` error).

This change is a potential breaking change (if your credentials include a `:` in either the identifier or the secret, your app will no longer work with `client_secret_basic`). You should make it opt-in.

**Comment by jdmichel** [comment]
This just cost our company an embarrassing amount of time and money to track down. It's mandated as optional in the OAUTH 2.0 spec, but required by the OIDC spec. Your current implementation isn't even allowed by the OIDC spec. 
And you knew about this BUG a year and a half ago?
The point of having a spec is that each implementer doesn't a get a vote about what they think makes sense for one reason or another. We implement a spec so that all the different solutions will be interoperable. For once, someone actually makes one of those rare and precious specs that isn't ambiguous and open to interpretation, and then your team decides to ignore it anyway. 
<sigh>

**Comment by jdmichel** [comment]
The identity provider for our company does not work if the client id and secret are included in the body. Any idp that does so is non-compliant.

I would be surprised if the change actually breaks any providers, but if it does, then the bug is on their end. At the very least, the default behavior should be compliant, and a simple flag could be added to do it the old way. 

Why would a colon or non-ascii char in the id or secret cause a problem? The spec says that the authorization header should be base64 encoded, so putting the id and secret directly into the header separated by a colon would also be non-compliant.

**Comment by kevinchalet** [comment]
> Why would a colon or non-ascii char in the id or secret cause a problem?

Historically, most of the OAuth2/OpenID Connect servers have implemented client_id/client_secret deformatting the same exact way you did, **which is sadly not compliant** as both the client_id and the client_secret MUST be formurl-encoded before being concatenated. Otherwise, you'll end up with weird errors if either your client_id or your client_secret contains a `:` or a non-ASCII character.

Read https://tools.ietf.org/html/rfc7617#section-2 for more information.

**Comment by jdmichel** [comment]
My PR didn't actually send credentials in both header and form. I only mentioned it in the Issue, because I was trying to think of a way to keep everyone happy. I agree it's a bad idea. 

I didn't read the whole spec, but I (maybe mistakenly) thought the OIDC was trying to simplify interop by mandating client_secret_basic. 

I see what you mean now by the colon. 

I also did notice the failure to specify UTF8, although it seemed to be implied by other places I noticed in the spec that did specify UTF8.  I'm well familiar with ambiguity problems in specs, having spent years making CORBA implementations interoperate. 

I also understand the resistance to making breaking changes. If I could get all of our (at least the newer core 2+) services to work out of the box with a one-line setting change instead of having to hack in a custom RedeemToken function then I would be very happy. Most of the teams at our company before me ended up either writing their own middleware from scratch, or even implementing the OIDC flows at  the app layer with controllers. I've been pushing for our latest project to build all of our services relying on the stock core 2 middleware as much as possible. I don't want us to be in the OIDC/OAUTH business.

**Comment by jdmichel** [comment]
Just had a brief read through the full spec. Yikes. 
I'll try to push our identity provider to at least support client_secret_post as an option, but it would still be nice if core 2+ at least supported client_secret_basic as an option since it was supposed to be the default.

**Comment by jdmichel** [comment]
For completeness, here's a link to the past discussion of this bug. https://github.com/aspnet/Security/issues/1032

**Comment by leastprivilege** [comment]
If the header is used for client authentication, it should use the encoding specified in RFC6749 - everything else is a bug.

**Comment by PinpointTownes** [comment]
@leastprivilege assuming you're referring to the formurl encoding, even that is quite risky as it has never been correctly implemented in many (if not most) OAuth2/OIDC implementations, including yours and mine :sweat_smile:

**Comment by PinpointTownes** [comment]
Curious: did you do that in a major release or in a minor one? Did you implement a quirk?

**Comment by leastprivilege** [comment]
minor. we got some error reports. People accepted it. My client lib has a "legacy mode". The world moved on.

**Comment by leastprivilege** [comment]
I just checked the OIDC certification tests - they test that the OP supports both the authz header approach as well as POST body.

So it's totally fine for the OIDC handler to POST client id/secret.

BTW - the OIDC handler should get certified. I always tell customers to pick software from that list: 
https://openid.net/certification/ - unfortunately the ASP.NET Core OIDC handler is not on it..

 @blowdart

**Comment by Tratcher** [comment]
In summary: We could add this but it would need to be optional opt-in.

Certification issue: https://github.com/aspnet/Security/issues/1197

**Comment by Eilon** [comment]
Triage discussion: While we think it could be good to support this, we are not taking this PR as-is because we think it needs to be opt-in (off by default, for compatibility), and we would likely also want to add additional test coverage.

**Pull request closed without merging**
