### PR TITLE
Replace magic strings by the new constants introduced in IdentityModel

### PR DESCRIPTION
**Pull request by PinpointTownes**
No functional change, only code cleanup.

/cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:+1:
As this is non-functional it does not current meet the bar for v1.0. We can merge it for 1.0.1 after branching for v1.0.

**Comment by PinpointTownes** [comment]
Sure :+1: 

Curious: is RTM still planned for late June?

**Comment by Tratcher** [comment]
So far so good...

**Comment by Tratcher** [comment]
Rebased and merged. Thanks

**Comment by PinpointTownes** [comment]
Thanks.

BTW, the milestone is named "1.0.1" but the `dev` branch builds "1.1.0" packages. Is this deliberate?

**Comment by Tratcher** [comment]
The 1.0.1 milestone is getting renamed to 1.1.0 soon.

**Pull request closed without merging**
