### PR TITLE
Add AddAuthentication(defaultScheme) overload

### PR DESCRIPTION
**Pull request by HaoK**
@Tratcher

### CODE REVIEW

**Comment by PinpointTownes** [comment]
That's a terrible idea. Folks will be tempted to call this middleware multiple times, resulting in all the `IAuthenticationRequestHandler` being invoked multiple times! :scream:

**Comment by HaoK** [comment]
Not quite, all that would result in is the DefaultScheme being set to the last one.  This is Add, not Use

**Comment by PinpointTownes** [comment]
Arf, my bad, doing too many at the same time :sweat_smile: 

So the only risk is that the first call will be ignored?

**Comment by HaoK** [comment]
Its not different than today, AddAuthentication(o => o.DoStuff()).AddAuthentication(o => o.DoMoreStuff()).

DoStuff() and DoMoreStuff() are called, so whatever side effects happen...happen :)

**Comment by PinpointTownes** [comment]
What I mean is that if you do `services.AddAuthentication("abc")` and then `services.AddAuthentication("xyz")`, the second call will override the first one? So the default scheme will be `xyz`, not `abc`?

If that how it works, then that's fine :smile:

**Comment by HaoK** [comment]
Yup, its just sugar for o => o.DefaultScheme = "abc"

**Comment by PinpointTownes** [comment]
Great, thanks, and sorry for the false alert. I'll stop doing too many things at the same time :trollface:

**Comment by HaoK** [comment]
Eh welcome to my world right now :)

**Pull request merged**
