### PR TITLE
React to Challenge changes

### PR DESCRIPTION
**Pull request by HaoK**
cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit:

**Comment by davidfowl** [comment]
Why does this fail on appveyor?

**Comment by HaoK** [comment]
How does appveyor work exactly?  This pr depends on a pr from http abstractions as well.

**Comment by davidfowl** [comment]
AppVeyor represents what you get if you clone and build. It isn't using the volatile feed so sweeping changes will cause breaks until coherence passes.

**Comment by HaoK** [comment]
9ce84d39c2c852e418eae13a6a984159343b4162

**Pull request closed without merging**
