### PR TITLE
Removed references to Shouldly

### PR DESCRIPTION
**Pull request by jmloeffler**
* removed Shouldy as a dependency from all tests
* could not enable coreclr50 due to remaining incompatibility with moq, Uri.GetLeftPart(...), UriPartial, et al

#420

### CODE REVIEW

**Comment by davidfowl** [comment]
@jmloeffler how many tests had that issue? We could skip those and file the appropriate bugs.

**Comment by jmloeffler** [comment]
It's not clear why the appveyor build failed.  Running `dnx test` from test\Microsoft.AspNet.Authentication.Test works for me.  Any guidance?

**Comment by jmloeffler** [comment]
I've got a branch with my spike trying to enable dnxcore50.  I got pretty close.  I'll put together a list of things that seemed to be in the way and post it here.

**Comment by davidfowl** [comment]
@jmloeffler would you be willing to send that in another PR? I want to get this change in. I'll try it locally to see if appveyor was a random failure.

**Comment by davidfowl** [comment]
Works for me as well. Might be a random failure.

**Comment by jmloeffler** [comment]
I just found an issue with my PR anyway where so I'm going to add a commit anyhow.  That should trigger a new build and we'll see what happens then.

**Comment by jmloeffler** [comment]
@davidfowl Do you want me to submit a separate PR for enabling `dnxcore50`?  I think that is what you were suggesting but I want to be clear.  It is a broken build but if you see value in it then it does show what remains to be worked if we want all of the test projects to be compatible.  I believe Microsoft.AspNet.Authentication.Tests is the only project without compatibility.  This commit message shows what remains as well if that is easier: 6248e21a3482e571820efabd3fc888954c7a4066

**Comment by Tratcher** [comment]
@jmloeffler I've already removed many of those in a related PR: https://github.com/aspnet/Security/pull/442/files#diff-63e5a4ec33f20ffdc309e9cd73b1c6f4

**Comment by jmloeffler** [comment]
@Tratcher Yeah that was a nice big block of dead code hiding a dependency on Moq.  I suppose after your PR goes through the commit I referred to will be moot (so there's no reason for me to PR it) and just the items I pointed out in the commit message will remain.  I'm not sure what to do about those.

**Comment by Tratcher** [comment]
GetLeftPart is an easy one, it just says give me the Uri up to and including the specified part. So GetLeftPart(UriPartial.Path) just means leave off the query and fragment. You can do something similar using GetComponents or UriBuilder.

**Comment by jmloeffler** [comment]
@davidfowl Do you want to create a separate issue for enabling `dnxcore50`?  It seems like that was a secondary goal for #420, which can now be closed.

**Comment by Tratcher** [comment]
@jmloeffler Go for it.

**Comment by davidfowl** [comment]
That would be great

**Comment by jmloeffler** [comment]
Issue #454 created

**Pull request merged**
