### PR TITLE
Fix #140 and rework the different OAuth2 Bearer middleware tests

### LINKED ISSUE #140: OAuthBearerAuthenticationNotifications.SecurityTokenValidated is never triggered
https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Security.OAuthBearer/OAuthBearerAuthenticationHandler.cs#L134-L148

/cc @brentschmaltz @Tratcher

### PR DESCRIPTION
**Pull request by PinpointTownes**
The PR is a bit noisy but I had to rework large parts of various tests, that were not really conclusive.

/cc @brentschmaltz @Tratcher

### CODE REVIEW

**Comment by msotclas** [comment]
Hi __@PinpointTownes__, I'm your friendly neighborhood Microsoft Open Technologies, Inc. Pull Request Bot (You can call me MSOTBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.msopentech.com.
    </span>

TTYL, MSOTBOT;

**Comment by msotclas** [comment]
__@PinpointTownes__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSOTBOT;

**Comment by PinpointTownes** [comment]
I love that bot :smile: (that said, I had already signed the CLA to submit a PR on CodePlex :hushed:)

**Comment by PinpointTownes** [comment]
Ping @brentschmaltz @HaoK @Praburaj @Tratcher

**Pull request closed without merging**
