### PR TITLE
Remove log codes from exception/log messages; don't localize logs

### PR DESCRIPTION
**Pull request by Eilon**
https://github.com/aspnet/Security/issues/414 and https://github.com/aspnet/Security/issues/418

Also started putting in event ids for logs.

@Tratcher @HaoK

### CODE REVIEW

**Comment by Eilon** [comment]
I focused on re-working the existing code without any significant changes. I didn't focus on whether the log *level* was right, or whether the messages were super useful. I did, however, correct smaller clarity issues in the messages.

**Comment by Tratcher** [comment]
:shipit:

**Comment by Eilon** [comment]
@Tratcher thanks!

**Comment by HaoK** [comment]
Do we need to worry about log event ids colliding from base classes?  Also looks a bit weird seeing random ints in the code like this.

**Comment by Eilon** [comment]
Hence my question to a bunch of folks yesterday. If each class uses its own type name as the category name then conflicts won't happen.

As far as ints being weird, well, they're arbitrary numbers, so they're always weird :smile: But they're unique within a category name (unless I messed one up!).

**Comment by HaoK** [comment]
Yeah this just feels a bit weird and error prone for the future, its not too bad right now with most of the classes having < 5 log sites, but I can imagine if we start getting having some files with 30+ logger calls, adding a new log code later on is going to result in a struggle to find what's the appropriate nextId(), especially if you add it in the middle, then file order is broken and anarchy ensues :)

**Comment by Eilon** [comment]
Yeah these are all good points. Clearly the event ids should be the SHA hash if the call site or something :smile:

**Comment by HaoK** [comment]
Yeah if we just want it to always be unique, seems better to just automagically make it so...

**Comment by Eilon** [comment]
It has to be two things:

1. Unique
2. Stable

Solving 1. is easy, but solving 2. is difficult.

**Comment by HaoK** [comment]
Sounds like something like how we name our unit tests is appropriate maybe?
"AuthFailureCuzNoClaim"
"AuthSuccess"
"CookieFailedValidationNoTicket"

**Comment by Eilon** [comment]
The codes are ints, not strings.

There's a category name, for which solving uniqueness is fairly easy: namespace+type name.

There's also an event id, which is an int, and has to be unique within a category name.

**Comment by HaoK** [comment]
Yeah so can't we just use hash code for a logical string to make it stable and uniquish?

**Comment by Eilon** [comment]
Well that's not stable across CLR versions either :frowning:

**Comment by HaoK** [comment]
We could write our own stable helper hasher then? `GenerateEventId("ZeroIsSoUgly")`

**Comment by Eilon** [comment]
Honestly I'm not sure that's much better. There's another proposal floating about that's suggesting using opaque strings, which while they certainly don't guarantee uniqueness either, are perhaps easier to deal with.

**Comment by Tratcher** [comment]
How about a pattern like this for bookkeeping?
```c#
internal static class FacebookEventIds
{
  public const int EventAbc1 = 1;
  public const int EventDef2 = 2;
}
```
I think you could do something similar with an `enum FacebookEventIds : int`.

**Comment by HaoK** [comment]
I like this more than the random ints sprinkled around.  Reminds me of the pattern Eilon just nuked with error codes :)

**Comment by Eilon** [comment]
Ah yeah sure I just looked at some EF code and I think they have a class with identifiers for all these.

Logged https://github.com/aspnet/Security/issues/532 and assigned to myself.

**Pull request merged**
