### PR TITLE
Remove the nonce cache.

### PR DESCRIPTION
**Pull request by Tratcher**
#434 
@HaoK @PinpointTownes @brentschmaltz 
cc: @Eilon @muratg

### CODE REVIEW

**Comment by Eilon** [comment]
:shipit:

**Comment by PinpointTownes** [comment]
If you really want to remove the server-side cache, I won't fight for it. But you have to realize that this nonce feature offers absolutely no protection against replay attacks... it's basically pointless here.

**Comment by Tratcher** [comment]
@PinpointTownes http://openid.net/specs/openid-connect-core-1_0.html#NonceNotes
The use of the cookie is specifically recommended to keep a 3rd party from resubmitting the same token. There's also the TVP.TokenReplayCache.

**Comment by PinpointTownes** [comment]
> The use of the cookie is specifically recommended to keep a 3rd party from resubmitting the same token. 

Yes, but if you don't check the nonce against already-used nonces, you can't detect replays. Again, preventing replay attacks is not mandatory (for both the code and the implicit flows), but clearly recommended by the specs.

> There's also the TVP.TokenReplayCache.

The problem with `TokenReplayCache` is that there's no default implemention (unlike WIF, that had a default in-memory implementation). Do you really think someone will ever implement it? Setting a bool to `true` was much easier :smile:

**Comment by Tratcher** [comment]
You forget the part about setting up a distributed cache.

**Comment by PinpointTownes** [comment]
Ah yeah, `services.AddCaching()` or (`services.AddRedisCache()` for a real distributed implementation) :smile:

**Comment by PinpointTownes** [comment]
The more I think about it, the more I realize that keeping `IDistributedCache` is not harmful. But I think it needs a better name to clearly indicates what it can be used for. What about renaming `CacheNonces` to `DetectReplayedTokens` (the name used by WIF) or `DetectReplayAttacks`?

**Comment by Tratcher** [comment]
@brentschmaltz? This still seems redundant with TokenReplayCache, no?

**Comment by Tratcher** [comment]
I think we're still going to remove it for now.

**Pull request merged**
