### PR TITLE
React to Kestrel https changes

### PR DESCRIPTION
**Pull request by Tratcher**
:-1:

### CODE REVIEW

**Comment by Tratcher** [comment]
@shirhatti

**Comment by HaoK** [comment]
Ewww?

**Comment by Tratcher** [comment]
Yeah, @davidfowl gets locked in a room with @DamianEdwards and his cricket bat for this one.

**Comment by davidfowl** [comment]
Merge it. It's blocking the ci. I acknowledge it's gross

**Comment by Tratcher** [comment]
Redundant with @halter73's change

**Pull request closed without merging**
