### PR TITLE
Reenable API check

### PR DESCRIPTION
**Pull request by HaoK**
@Tratcher

### CODE REVIEW

**Comment by HaoK** [comment]
🤢 Fixes https://github.com/aspnet/Security/issues/1160

**Comment by Tratcher** [comment]
Did you want to get https://github.com/aspnet/Security/pull/1243 in first?

**Comment by HaoK** [comment]
Nah, we'll just update the baselines again as part of merging that PR.  This at least makes things in a good state

**Comment by Tratcher** [comment]
@muratg what's the plan for reviewing all the breaks before RTM?

**Pull request merged**
