### PR TITLE
Honor OIDC's OnAuthenticationFailed HandleResponse()

### PR DESCRIPTION
**Pull request by Tratcher**
# 884 @HaoK this fills in a gap in the event flow. What do you think?

I still need to try it with other events, other middleware, and add tests.

### CODE REVIEW

**Comment by HaoK** [comment]
Yes this looks like a much better :)

**Comment by Tratcher** [comment]
Updated with a similar approach to make JwtBearer work

**Comment by Tratcher** [comment]
@HaoK I added a lot of JWT and OIDC tests. I found two oddities beyond the original bug.
https://github.com/aspnet/Security/pull/1008/files#diff-89f4ccfea34a2fdaef439f48cf2d2547R195
1. Some of the events did not include the current AuthTicket, I added it.
2. Some of the events when Handled still result in the TicketReceived event being invoked and the cookie set. I think this original code (https://github.com/aspnet/Security/pull/1008/files#diff-a771d2d9b96202c4add713e120e832dbL54) where Handled events returned a ticket was wrong, Handled was documented to say the caller generated a complete response, not that they generated a Ticket and short circuited some of the validation logic. I worry a little that changing it will break former users of Handled (if any), and also that fixing #1 above will cause the same thing to start happening for other events. Of the two I think it'd be better to break Handled behavior to discard the Ticket as it didn't work in many scenarios anyways (hence the original bug).

Thoughts?

**Comment by Tratcher** [comment]
@HaoK Updated.

**Comment by PinpointTownes** [comment]
@Tratcher curious: how urgent is this? I'd like to test it with the aspnet-contrib stuff to make sure the new `AuthenticateResult.Handle()` semantic doesn't break anything.

**Comment by Tratcher** [comment]
@PinpointTownes how long do you need? I'd like to get it in this week.

**Comment by PinpointTownes** [comment]
I'll give a try tomorrow morning.

Do you know if a recent `Microsoft.NETCore.App` package is needed to play with the ASP.NET Core 1.1.0 bits?

**Comment by Tratcher** [comment]
You likely need preview1

**Comment by PinpointTownes** [comment]
@Tratcher FYI, I've run all the aspnet-contrib tests and everything is green (the OAuth2 introspection/validation middleware also use `HandleResponse()` as a way to bypass the default validation logic, but they return `AuthenticateResult.Skip()`, so the behavior is not changed in practice).

> I worry a little that changing it will break former users of Handled (if any), and also that fixing #1 above will cause the same thing to start happening for other events. Of the two I think it'd be better to break Handled behavior to discard the Ticket as it didn't work in many scenarios anyways (hence the original bug).

It's indeed an important change but I agree it makes more sense than leaving it as-is. If this change is approved, I'll rework the aspnet-contrib middleware to match the new logic used by the built-in middleware.

**Comment by PinpointTownes** [comment]
Note that while I think this change is positive, I'm a bit concerned about not being able to bypass the default token validation logic without handling the complete response. You might want to add some `context.Ticket != null` checks to restore the `context.HandleResponse()` behavior.

**Comment by PinpointTownes** [comment]
It would also be worth adding a tiny comment somewhere to indicate that `AuthenticateResult.Handle()` doesn't really stop processing the request when the authentication middleware is invoked via `AuthenticationManager.SignInAsync`, instead of as part of automatic authentication.

**Comment by Tratcher** [comment]
The trouble is that the Ticket is almost always not null, so that's not a good indicator of what HandleResponse should do. Have you actually seen anyone provide a Ticket and skip the remaining validation? If so was it for Jwt or OAuth?

The only additional behavior that HandleResponse would skip if there were a Ticket is the last section of HandleRemoteCallbackAsync: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authentication/RemoteAuthenticationHandler.cs#L83-L115

If we really want to preserve the ability to skip from the middle of the validation logic all the way to HandleRemoteCallbackAsync then we may need a third state: SkipToNextMiddleware, SkipRemainingValidation, and HandledResponse.

**Comment by PinpointTownes** [comment]
> The trouble is that the Ticket is almost always not null, so that's not a good indicator of what HandleResponse should do. Have you actually seen anyone provide a Ticket and skip the remaining validation? If so was it for Jwt or OAuth?

Yep, but only once or twice, so I suppose it's not that frequent. IIRC, it was from `OAuthValidationEvents.RetrieveToken`, the equivalent of `JwtBearerEvents.MessageReceived` in the contrib world. The cool thing with this event is that there's no ticket yet, so we can easily add a null check.

The real question is more about the intermediate events (e.g `OpenIdConnectEvents.TokenResponseReceived` or `OpenIdConnectEvents.TokenValidated`), that are called at the middle of the authentication process. FWIW, I've personally never used `HandleResponse` from these events (which doesn't mean no one else is relying on this behavior :smile:)

**Comment by PinpointTownes** [comment]
Random idea: wouldn't a reference equality check be an interesting alternative to `HandleResponse` for this scenario?

If the ticket was replaced, stop the validation process and use it as-is.
If it was not replaced, continue the validation process.

**Comment by Tratcher** [comment]
A ticket replacement check seems pretty weak.

I went back and looked at how this worked in Katana. A Handled event would only ever return an empty ticket. This was changed when OIDC was first moved to Core.
http://katanaproject.codeplex.com/SourceControl/latest#src/Microsoft.Owin.Security.OpenIdConnect/OpenidConnectAuthenticationHandler.cs
https://github.com/aspnet/Security/commit/49e66f03110b486f8dd9959dd2cee802d676c28f#diff-d9d4f83dd99a371877f472e7c4611b29R87

Interestingly the comment for Ticket has said the same thing the whole time: `Gets or set the <see cref="Ticket"/> to return if this event signals it handled the event.` I overlooked the comment on HandleResponse that said `Set the <see cref="Ticket"/> to trigger SignIn.`. So it seems the intended behavior was for people to null out Ticket if they didn't want SignIn to be called (like the last iteration of my tests did). That seems really strange.

**Comment by Tratcher** [comment]
Hmm, logical elimination: nobody could call HandleResponse in AuthenticationFailed or TokenResponseReceived without specifying a ticket because it would have thrown before (hence #884). All the other events already had a ticket so if they called HandleResponse then that would have resulted in SignIn. I will add the ticket to TokenResponseReceived for consistency with the other events, but not to AuthenticationFailed because it would be bad for a failed auth to accidentally sign-in.  Then I'll allow ticket to be nulled out if you didn't want to call sing-in. This is the least likely to break anyone this release, and fixes the main bug in AuthFailed.

**Comment by HaoK** [comment]
That sounds reasonable, and at least you've added more test coverage for this behavior now :)

**Comment by Tratcher** [comment]
Updated / reverted

**Comment by Tratcher** [comment]
https://github.com/aspnet/Security/issues/772

**Comment by PinpointTownes** [comment]
The fact `HandleResponse()` doesn't have the same behavior when `Ticket` is null is frankly weird, but I guess it's one of those "better than nothing" compromises :shipit:

**Pull request merged**
