### PR TITLE
Partly fix google access deny

### PR DESCRIPTION
**Pull request by Anderman**

### CODE REVIEW

**Comment by Tratcher** [comment]
FYI: There's some heavy refactoring in progress around this: https://github.com/aspnet/Security/pull/495

**Comment by Anderman** [comment]
Fine, I'll wait for the new version

**Comment by HaoK** [comment]
The refactoring has been merged if you would like to rebase/update this PR we can take a look then

**Comment by muratg** [comment]
@Tratcher Does your update to the providers make this moot?

**Comment by Anderman** [comment]
I don't think it needed anymore. The changes looks good to me

**Comment by muratg** [comment]
Thanks @Anderman!

**Pull request closed without merging**
