### PR TITLE
Update Json.NET to 9.0.1-beta1

### PR DESCRIPTION
**Pull request by javiercn**

### CODE REVIEW

**Comment by Tratcher** [comment]
JwtBearer and OpenIdConnect both depend on this too, by I can't see where the dependency is declared.

**Comment by PinpointTownes** [comment]
@Tratcher https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/blob/KDev/src/Microsoft.IdentityModel.Tokens/project.json#L6

**Comment by javiercn** [comment]
Good catch, we probably want to add the reference to the project.json directly to force it to the right version? @pranavkm

**Comment by dougbu** [comment]
@javiercn we _like_ transitive references

**Comment by Tratcher** [comment]
@javiercn file a bug in AzureAd for them to upgrade to the same version. I assume there's a plan for RTM?

**Comment by javiercn** [comment]
@Tratcher I would think so, but will check with @Eilon

**Comment by Eilon** [comment]
Fix for now here, but also log a bug in AzureAD.

**Comment by javiercn** [comment]
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/431

**Pull request merged**
