### PR TITLE
Prototype shared AuthorizationPolicyEvaluator

### PR DESCRIPTION
**Pull request by HaoK**

### CODE REVIEW

**Comment by davidfowl** [comment]
@HaoK did you ever file an issue for this to do as part of 2.0?

**Comment by HaoK** [comment]
Its on my todo list as part of AuthZ 2.0, which should happen in preview 2

**Comment by HaoK** [comment]
https://github.com/aspnet/Security/issues/901 is the main one for AuthZ

**Comment by HaoK** [comment]
Meta tracking issue for Auth 2.0 todo list for preview 2 https://github.com/aspnet/Security/issues/1190

**Comment by HaoK** [comment]
Moved into https://github.com/aspnet/Security/pull/1193

**Pull request closed without merging**
