### PR TITLE
OAuthContext should set user, add test

### PR DESCRIPTION
**Pull request by HaoK**
Well at least it appears the tests do catch some stuff :)

@PinpointTownes you forgot to set User...  let me tell you, that causes some weird obscure failures in our functional...  Added a sane test to verify the context properties.

### CODE REVIEW

**Comment by PinpointTownes** [comment]
Meh, I suck. I'm pretty sure I added this bug when splitting the constructors... shame on me! :boom:

**Comment by HaoK** [comment]
Its ok, you finally forced me to delve into the music store tests...and I plugged a test hole :)

**Comment by PinpointTownes** [comment]
Heh, at least my bug had a merit :smile: #wrongjustification

**Comment by HaoK** [comment]
61bbe4cf52a3a204a94e041c810bedc6ee8867f3

**Pull request closed without merging**
