### PR TITLE
Support specifying DataProtector in CookieOptions

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Security/issues/259

cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
:shipit:

**Comment by PinpointTownes** [comment]
Curious: why not providing a `options.UseDataProtector(protector)` extension to avoid having two disconnected properties (`TicketDataFormat` vs `DataProtector`)?

```csharp
public static CookieAuthenticationOptions UseDataProtector(this CookieAuthenticationOptions options, IDataProtector protector) {
    options.TicketDataFormat = new TicketDataFormat(protector);

    return options;
}

**Comment by Tratcher** [comment]
@PinpointTownes I asked him to hold onto it because I'm going to need it later for https://github.com/aspnet/Security/issues/263

**Comment by PinpointTownes** [comment]
@Tratcher I'm a total noob concerning this new TLS extension, but isn't this new token a per-client thing? I'm not sure to understand how being able to set a global data protector (i.e shared by the different clients) may be related to this feature.

**Comment by Tratcher** [comment]
@PinpointTownes IDataProtector lets you create a derived protector. If the client is providing key data then your encryption needs to take into account both the server keys and the client keys.

**Comment by PinpointTownes** [comment]
@Tratcher, so the cookies middleware will directly use `Options.DataProtector` instead of `Options.TicketDataFormat` but only when `Options.DataProtector` is explicitly set?
IMHO, it doesn't seem very intuitive.

Instead, have you considered refactoring `ISecureDataFormat.Protect`/`ISecureDataFormat.Unprotect` to take an additional parameter that could be used to flow this new TLS binding token?

https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNet.Authentication/DataHandler/SecureDataFormat.cs

**Comment by PinpointTownes** [comment]
Something like that:

```csharp
public string Protect(TData data, string purpose)
{
    var protector = _protector;
    if (!string.IsNullOrEmpty(purpose))
    {
        protector = protector.CreateProtector(purpose);
    }

    var userData = _serializer.Serialize(data);
    var protectedData = protector.Protect(userData);
    var protectedText = _encoder.Encode(protectedData);
    return protectedText;
}
```

```csharp
public TData Unprotect(string protectedText, string purpose)
{
    try
    {
        var protector = _protector;
        if (!string.IsNullOrEmpty(purpose))
        {
            protector = protector.CreateProtector(purpose);
        }

        if (protectedText == null)
        {
            return default(TData);
        }

        var protectedData = _encoder.Decode(protectedText);
        if (protectedData == null)
        {
            return default(TData);
        }

        var userData = protector.Unprotect(protectedData);
        if (userData == null)
        {
            return default(TData);
        }

        var model = _serializer.Deserialize(userData);
        return model;
    }
    catch
    {
        // TODO trace exception, but do not leak other information
        return default(TData);
    }
}
```

**Comment by Tratcher** [comment]
Hmm, it may come to that. We haven't worked through the details yet.

**Comment by PinpointTownes** [comment]
In this case, I guess that this new `DataProtector` property won't be necessary :smile:

**Comment by HaoK** [comment]
@Tratcher Where did we end up finally on this?  Can we just replace the data protector now?

**Comment by Tratcher** [comment]
@PinpointTownes is probably right, we don't need to save the DP on the options, at least not yet.

**Comment by HaoK** [comment]
Ok so now this PR basically only consists of adding a test to verify that we can share data protectors in two different TicketDataFormats.  We are happy with the existing TicketDataFormat extensibility correct?

**Comment by Tratcher** [comment]
Yes, for now.

**Comment by HaoK** [comment]
a3f0ee3330e936cad13b4391a1f7a13ff26764fd

**Pull request closed without merging**
