### PR TITLE
Set DisplayName for OAuth + Twitter

### PR DESCRIPTION
**Pull request by HaoK**
@Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
Can you add this back to the Social sample?

**Comment by PinpointTownes** [comment]
Interesting, I was about to open a new ticket to reintroduce `DisplayName`.

The problem with this PR is that there are now 2 disconnected properties: one in the scheme handler configuration, and one in the scheme options. FWIW, I'm not a huge fan of using the scheme as the display name by default. Why not hardcoding the provider name, just like in 1.0.0?

**Comment by HaoK** [comment]
Yeah we can iterate on how this lands for preview 2, but I need to get working templates this week, so I'm doing the bare minimum to put out the fires :)

We probably want overloads for AddXyz that let you specify the display name I guess longer term.

**Comment by HaoK** [comment]
Oh yeah and the display name in the handler configuration is going to get nuked...

**Comment by HaoK** [comment]
4f206558505b32c5ec0a686764ec30a8f912860e

**Pull request closed without merging**
