### PR TITLE
Discriminate between providers when sharing an auth cookie

### PR DESCRIPTION
**Pull request by Tratcher**
#859 @Haok

This prevents `[Authorize("Github")]` from returning an identity produced by Facebook, etc. when they share a cookie middleware.

### CODE REVIEW

**Comment by HaoK** [comment]
Can you also add a test exercising the template flow which uses a shared External cookie as opposed to named google/facebook cookies.

**Comment by Tratcher** [comment]
I don't follow, they already do use a shared cookie. https://github.com/aspnet/Security/pull/980/files#diff-f6bd2d01f6e995e0fa83a42bb849b920R1010

**Comment by HaoK** [comment]
The configure code path the templates/identity use is slightly different, they use SharedAuthenticationOptions.SignInScheme, would be good to make sure that identity/template configuration works as well with this change

**Comment by Tratcher** [comment]
SharedAuthenticationOptions is being used here: https://github.com/aspnet/Security/pull/980/files#diff-f6bd2d01f6e995e0fa83a42bb849b920R1103

**Pull request merged**
