### PR TITLE
Remove username from AuthZ logging

### PR DESCRIPTION
**Pull request by HaoK**
Fixes https://github.com/aspnet/Security/issues/1259

@Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
It's a start, but @blowdart had a laundry list of things we should remove beyond this item.

**Comment by HaoK** [comment]
Also removed token logging, @blowdart what else did you want us to stop logging?

**Comment by PinpointTownes** [comment]
If you had to debug real world apps having authentication issues every day, you'd never dare remove that... :trollface:

**Comment by blowdart** [comment]
I know, but GPDR says no personal identifying information without protecting it, and we cannot know how logs are protected.

However I will email the lawyers just to check.

**Comment by blowdart** [comment]
I can see the other side "Microsoft software helped my company get fined 10% of our global income". I'm going to leave this up to legal :D

**Comment by HaoK** [comment]
@blowdart what's the call here?

**Comment by blowdart** [comment]
Still waiting. In theory, "if we do not retain the data it is our customers responsibility to service DSR requests."

Now we'd have to then add something into logging to allow us to search in the templates. Which is a challenge.

**Comment by leastprivilege** [comment]
Move it to trace logging - that can by definition (aka according to your docs) contain "sensitive" data.

**Comment by PinpointTownes** [comment]
@leastprivilege you're a little late to the party... this was discussed in the main thread :sweat_smile: 

https://github.com/aspnet/Security/issues/1259#issuecomment-335627995

**Comment by Tadimsky** [comment]
Any updates on this PR?

**Comment by HaoK** [comment]
ba1eb281d135400436c52c17edc71307bc038ec0

**Pull request closed without merging**
